service: serverless-ddns 

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1


custom:
  myStage: ${opt:stage, self:provider.stage}
  customDomain:
    domainName: dev.myip.belisleonline.com
    # stage: 
    # basePath: api
    certificateName: 'dev.myip.belisleonline.com'
    createRoute53Record: true
    endpointType: 'edge'  

plugins:
  - serverless-domain-manager  
  # - serverless-aws-alias

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  echo-ip:
    handler: src/echoip.handler
    role: basicLambdaRole
    memorySize: 128
    events:
      - http:
          path: /
          method: GET
  update-home-dns:
    handler: src/updateHomeDNS.handler
    role: lambdaUpdateRoute53Role
    memorySize: 128
    environment:
      DNS_HOST_NAME: home.belisleonline.com
      HOSTED_ZONE_ID: Z1E1E8WAILPZ5
      TOPIC_ARN: arn:aws:sns:us-east-1:197556904653:NotifyMe
    events:      
      - http:
          path: /      
          method: POST
          authorizer:
            type: aws_iam                     
resources:
  Resources:
    basicLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: BasicLambdaRoleServerlessDDNS
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole        
        Policies:
          - PolicyName: BasicLambdaRoleLoggingPolicy
            PolicyDocument:            
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:*:*:*
    
    lambdaUpdateRoute53Role:
      Type: AWS::IAM::Role
      Properties:
        RoleName: UpdateLambdaRoleServerlessDDNS
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole        
        Policies:
          - PolicyName: UpdateRoute53LambdaRolePolicy
            PolicyDocument:            
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:*:*:*
                - Effect: Allow
                  Action:
                    - route53:*
                  Resource:
                    - "*"
                - Effect: Allow
                  Action:
                    - sns:Publish
                    - sns:Subscribe
                  Resource: arn:aws:sns:us-east-1:197556904653:NotifyMe
    InvokeUpdateHomeDDNSAPIPolicy:
      Type: "AWS::IAM::ManagedPolicy"
      Properties:
        Description: "Policy for allowing invoke access to the updateHomeDDNS secured API"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            Effect: Allow
            Action: execute-api:Invoke
            Resource: { "Fn::Join" : ["", ["arn:aws:execute-api:",{"Ref":"AWS::Region"},":",{"Ref":"AWS::AccountId"},":",{"Ref":"ApiGatewayRestApi"},"/*"]]}
    APIUser:
      Type: "AWS::IAM::User"
      Properties:
        ManagedPolicyArns:
          - { "Ref": "InvokeUpdateHomeDDNSAPIPolicy" }
        UserName: update-homeddns-api-user    